- code/modules/mob/living/carbon/human/species/races/nids.dm
- code/modules/mob/living/carbon/human/unarmed_attack.dm
Tyranids can no longer summon Ripper Snakes or Spit Neurotoxin which were both broken.
Tyranid Hissing sound removed so they can actually stealth.
Tyranid Health increased to 300. Brute/Burn resistances lowered.
Tyranid Melee damage reduced to 30+STR and removed Edge, more or less their damage is equal to a human using a Power Sword now but they attack faster.
> Tyranid Fix

- code/modules/clothing/suits/armor.dm
- code/modules/clothing/under/jobs/security.dm
I changed the description for the Progena's Power Armor, and the Sister of Battle Body suit
For the Student Power Armour, it made more sense to distance it from power armor that WOULD be active in a combat zone, as this is old armor that has been restored to just functionality to train students in wearing heavy armor and caring for it
And for the Sister of Battle Bodysuit... As funny as it is calling people coomers, if we ever add the ability to inspect the equipment on people it wouldn't make much sense, and it does feel a little out of tone
Anyway here is the compile, even though it was a few text changes
> Description Changes for Two things that needed it

- code/_global_vars/misc.dm
- code/modules/admin/admin_verbs.dm
- code/modules/mob/observer/lateparty.dm
This adds a bit more warning and text to the steps of queuing as a group for the late party. 
It contains a new admin verb to control the party size, default is 3. 3 separate groups will be sent before an admin needs to intervene and allow more.
> Group lateparty 2.0

- code/modules/cargo/armor.dm
- code/modules/cargo/categories/armor.dm
- code/modules/cargo/categories/blackmarket.dm
- code/modules/cargo/categories/melee.dm
- code/modules/cargo/categories/weapons.dm
Fixes bad references and missing item sprites by removing the items added that did not have sprites such as Machete and Sabre.
> Cargo Fixes

- code/_helpers/global_lists.dm
- code/game/jobs/job/adeptus_astartes.dm
- code/game/jobs/job/adeptus_mechanicus.dm
- code/game/objects/items/weapons/mop.dm
- code/game/objects/items/weapons/soap.dm
- code/game/turfs/flooring/flooring.dm
- code/game/verbs/ooc.dm
- code/modules/client/client_procs.dm
- code/modules/client/preference_setup/general/03_body.dm
- code/modules/detectivework/tools/rag.dm
- code/modules/mob/living/carbon/human/vice.dm
- code/modules/mob/logout.dm
- code/modules/mob/shit_piss.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
This has a bit of stuff in it.
**Vices:**
1. Lho is now the default vice to avoid making new players drunk.
2. Glutton has been fixed, you can now be happy again.
3. view range has been reduced for neat freak
4. Reworked how to handle alcohol and obscura. You no longer need to be perma blackout, if the reagent is in your blood stream your need will tick down. This means a sip every few minutes should keep you covered. Obscura is still going to make you high as balls tho.
5. Asstardes and Mech boys get no vices for now.
**SQL:**
1. Added better coverage for played time logging.
2. Now logs on mob logout, empties var to prevent dupes
3. Logs on client closing, empties the var to prevent dupes
4. In the OOC tab there is now a verb called 'View Played Time' to see your tracked alive played …
> Vice tweaks, better logging coverage

- code/game/objects/items/devices/mechanicustoys.dm
- code/modules/mob/living/carbon/human/species/station/skitarii.dm
Neural adapter can send highly visible messages to ghosts about available skitarii roles, now you can be sure that everybody knows about your little cog army
> Neural adapter new feature

- code/modules/cultist/deities.dm
- code/modules/cultist/effects/nurgle.dm
1. Zombie: Makes the cultist more durable. No pulse, visibly decayed(Flavortext)
2. Heal: Lets nurgle cultists heal wounds, but they take toxin damage.
> Nurgle abilities

- code/modules/cargo/cargoterminal.dm
So, how does it works?
By buying mercenaries from the category of common and elite, RT opens up job slots for them so that more players can enter for a certain role. You can open up only job slots taken by other players . For example, if we have 2 slots for guardsman, and 1 slot was taken by player, you can buy 1 more so we will have 2 slots again. So you can't hire whole army of Scions (unless you will sit near console whole round and spamming hire button)
But when you buying a xeno mercenary - it spawns a body with no ghost inside. You can send a request to ghost by using RT ring on mercenary body, just like neural coil of Biologis. If you bought an Ork mercenary, he will work for you. But he is still an Ork, and his behavior will be like that of an Ork. The more xenos you buy and the …
> Rogue Trader mercs buying!

- code/game/jobs/job/pilgrims.dm
This PR adds two new fates to pilgrim, in the form of Private Investigator and Cleric.
This PR also changes the name of Bounty Hunter into "Mercenary" to allow for more freedom on the players end.
Private Investigator is a role intended for minor investigative work below the nose of the Inquisition and Magistratum. They may solve issues such as petty thefts and disappearances, for a cost. While they have access to forensic equipment, they do not have anywhere to analyze it. This makes the PI have to either bribe or convince the Magistratum to allow them to use their equipment. 
Cleric is an extremely low-level member of the Minitorium who is supposed to preach to the local populace. They are utterly broke and have no short of shelter. They are generally equipped with very little, and …
> Minor Pilgrim Expansion

- code/game/objects/items/weapons/material/twohanded.dm
- code/modules/projectiles/guns/projectile/mattguns.dm
Rad Carbines now have in-hand sprites so no state of them should be invisible now, The fire axe has had its code changed to point to the right DMI file now so it is also no longer invisible.
- Rad Carbine has In hands
- Fire axe is not Invisible
> Weapon Sprite fix

- code/_helpers/mobs.dm
- code/game/objects/items/weapons/stunbaton.dm
- code/modules/mob/living/carbon/human/species/races/nids.dm
- code/modules/mob/living/carbon/human/species/races/orks/abilities.dm
Gives nids a verb to unsheathe their venom talon. When dropped the talon is auto deleted. So thats the only real way of re-sheathing it. Tried fucking around with the mechanicus stuff to copy it but didnt work and this works spaghettiy enough
Renames ork waagh ability to properly cost only 1 in the verb tab. Reminder all it does rn is fix eyes for 1 second, so if orks are under giga hurt its actually worth it to wagh every few seconds to see where you are
adds 40 new ork names and a few ogryn names
> Cherubael 0.157

- code/modules/mob/living/carbon/human/examine.dm
- config/admin_ranks.txt
Nurgle Cultists can no longer be meta'd by their examine text round start.
Trial Admins have more access permissions for debug and log diving, previously they could not access server logs properly. Now they can.
> Admin / Cult Fix

- code/game/objects/items/weapons/stunbaton.dm
- maps/warhammer/jobs/xenos.dm
This fixes the power maul by lowering the agony and raising the force. This makes it a two hit knockdown most of the time, but RNG changes this, obviously.
> Power Maul Balancing Update (super small)

- code/game/area/areas.dm
- code/game/sound.dm
- code/modules/client/preference_setup/global/preferences.dm
The 'play ambience' preference doesn't work, only cutting off the current and playing it like usual when you enter a different area.
'Toggle music' in OOC has the exact same function but actually works.
This has already confused one player, farewell play ambience preference.
> Removes Ambience Preference

- code/game/gamemodes/warfare/structures.dm
Lets sword subtypes cut through barbed wire again.
> Fixes barbed wire

- code/game/objects/effects/landmarks.dm
- code/modules/projectiles/guns/projectile/mattguns.dm
- code/modules/projectiles/projectile/special.dm
Bolter does higher damage(+10) but no longer causes explosions, it's property for sharp/edge are also removed. This should mean in terms of damage it is higher, but in actual effect it's much weaker since it can't insta decap or do extra explosion damage.
Chances for the Locke Bolter to spawn are reduced and it's fire delay is 2.45 instead of 2.4
It also has a minor increase to burst spread, so ideally don't use a Lockebolter in burst mode if you want accurate shots.
> Bolter Edit

- code/game/jobs/job/astra_militarum.dm
The default medicae role (WHICH YOU SHOULD NOT USE) now defaults to the Cadian gear.
> Medicae Patch

- code/game/jobs/job/magistratum.dm
- code/modules/cultist/effects/nurgle.dm
- code/modules/cultist/runes/nurgle.dm
- code/modules/mob/transform_procs.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
- code/modules/virus2/effect.dm
- maps/delta/warhammer_areas.dm
Misc;
Fixed Magistratum Headset to be Guard Issue and Medicae Power Issues.
NURGLE;
Modified Toughen Rite to grant +4 Endurance instead of +5
Modified Heal Rite to heal less and cause Toxin Damage as it was initially balanced. The original text of the rite is that it is meant to poison you in exchange for healing which it did not currently.
Modified Blightnade to have less Knockdown and Zombie Plague to not have slowdown. Noticed significantly in testing that zombies were never a threat to anyone on account of being too slow to catch their victims, quite literally snails would be faster then them. The knockdown from the Blightnade also made it so those turned into zombies couldn't really get up and be a threat for quite a long time. 
Slight edits to the Nurgle Plague Virus - which is …
> Minor Edits / Nurgle

- code/modules/clothing/shoes/jobs.dm
Remove the Kroot Foot sprite since the new species sprites covers that pretty well and the old kroot foot icons are made for the old model
Also adds noslip to the ork shoes, to put them on Par with the other late parties
> Remove Kroot Foot Sprite

- code/game/jobs/job/pilgrims.dm
This PR changes the Pilgrim role to have an 100% cult chance. I have not seen a single person who enjoys the new system, and many express frustrations and not being able to play the role (which is supposed to have freedom) how they wish. Rounds have also be consistently less enjoyable due to less heretical activity occurring, which is the main point of the game. Truth be told, non-heretic pilgrim is simply not fun for the people who want to roll cultist.
> Pilgrim Fix  (100% cult chance)

- code/game/objects/auras/aura.dm
Making a second PR actually, a little bit of foresight tells me we want toxin death to be quicker. Because players being stuck in crit just isn't fun at all for them.
For Nids we want them to actually heal from Crit since in Lore we know that sort of like Astartes Tyranids have redundant organs and sometimes extra brains. Sort of reminded by a Magos who remarks that even after seeing a genestealer strain blown to pieces and had been melted to the floor, it was still trying to obey the hivemind -- before they executed it with a lasbolt to the head.
Lastly we want Orks and Astartes to be more vulnerable to burns then brute, since burns biologically are harder to heal. Though Tyranids will heal their brute/burn at the same rate since they're hyper evolved predators.
> Aura Edit - Post Test

- code/modules/research/designs.dm
TECH_MATERIAL = 2, TECH_BIO = 3, TECH_DATA = 4, TECH_BLUESPACE = 3, TECH_ILLEGAL = 4
Because you need to unlock all implants in order to reprogram them. Very fair.
> Implant pad added to protolate

- code/game/antagonist/outsider/ert.dm
Fixes the ERT welcome text so the head of Messina is no longer the Rogue Trader. Your time to shine Gov'na
> ERT hotpatch

- code/game/jobs/job/astra_militarum.dm
Increases base guardsmen spots by 2 and other special guardsmen slots by 1, making the total guard count be from 8 to 13. Expands the Guard so it can be better used in rounds with more pop.
> Guardsmen Slot Increases

- code/modules/mining/oresningots.dm
Gemcutting broke because of an update, this will fix it.
Compiles
And works
> Fixes Gemcutting

- code/game/gamemodes/warfare/turfs.dm
- code/modules/reagents/reagent_containers/food/snacks.dm
Made all trench related construction activities significantly faster. Guardsmen should now not have to spend 45 minutes every round staring at a progression bar.
Also buffed the sale price of some raw types of meat gotten from simple mobs as part of an economy update.
> Trench Speed Buff & Meat Price Update

- code/game/jobs/job/astra_militarum.dm
Fixed several Valhalla jobs having botched loadouts with mismatching gun magazines, thanks to Lyaridas for reporting it on the discord.
> Valhallan Loadout Fixes

- code/game/jobs/job/astra_militarum.dm
Gave the Valhalla troops their proper Grim-pattern autoguns and made so that guardsmen don't RNG roll into being inept baboons when it comes to digging holes in the ground. Could do with a new skill specifically for trenches but engineering will do for now.
> Valhalla Gun & Skill fixes

- code/modules/cultist/effects/nurgle.dm
Wounds will no longer be covered with kittens. Removed toxin being added. Made it stronger but also added a cooldown and removed the ability to spam it when you're super dead.
> Nurgle Heal Rework

- code/game/jobs/job/astra_militarum.dm
- code/modules/clothing/clothing.dm
- code/modules/clothing/clothing_accessories.dm
- code/modules/clothing/head/helmet.dm
- code/modules/clothing/suits/armor.dm
- The kasrkin is no longer neon, but why they won't put on their gloves, I don't know. They'll find them in their pocket instead.
- Whiteshields have actual ingame flakvests now instead of a missing sprite.
- Some accessory code has been uncommented so that players can view accessories others are wearing, on their clothes and also remove them from said clothes.
> Reenables some accessory code and minor fixes

- code/modules/mob/observer/ghost/ghost.dm
ghosts that respawn or claim skitarii will be pulled into lateparty groups without this fix, probably are more ways of getting it with isreadied set to 1 though.
> lateparty bug fix

- code/datums/outfits/civilian.dm
- code/game/jobs/job/adeptus_ministorum.dm
- code/game/jobs/job/pilgrims.dm
- code/game/mecha/equipment/weapons/weapons.dm
- code/game/objects/items/weapons/cane.dm
- code/game/objects/items/weapons/melee/energy.dm
- code/game/objects/items/weapons/melee/misc.dm
- code/game/objects/items/weapons/swords_axes_etc.dm
- code/modules/clothing/head/helmet.dm
- code/modules/clothing/head/jobs.dm
- code/modules/clothing/head/misc.dm
- code/modules/clothing/suits/armor.dm
- maps/delta/warhammer-1.dmm
- maps/delta/warhammer-2.dmm
- maps/delta/warhammer-3.dmm
- maps/delta/warhammer-4.dmm
Added the Witch Hunter sub-fate to the Mercenary Pilgrim Fate. With unique witch hunter armor.
Updated a number of melee weapons to now provide a basic ranged defense -- with the greatest defenses being offered from the Daemonhammer and the Powersword, as it can often be underwhelming to wield incredible daemon slaying weapons that genuinely make no difference in your protection. Hopefully people feel more encouraged to do melee knowing that choosing a big ass sword means you are slightly more protected then if you were wielding a gun. The canon idea is -- someone using a sword will be moving faster then if they were using a gun. Pulling a trigger accurately requires you stay still. Swinging a sword is the opposite.
Updated the mech missile rack to only have 2 missiles per reload instead …
> Second Breakfast

- code/game/jobs/job/adeptus_astartes.dm
- code/game/jobs/job/magistratum.dm
- code/game/objects/items/devices/mechanicustoys.dm
- code/game/objects/items/weapons/storage/backpack.dm
- code/modules/clothing/rings/rings.dm
- code/modules/clothing/suits/utility.dm
- code/modules/clothing/under/accessories/holster.dm
- code/modules/projectiles/ammunition/boxes.dm
- code/modules/projectiles/guns/energy/laser.dm
- code/modules/projectiles/guns/energy/pulse.dm
- code/modules/projectiles/guns/energy/special.dm
- code/modules/projectiles/guns/launcher.dm
- code/modules/projectiles/guns/launcher/recoilless.dm
- code/modules/projectiles/guns/projectile/automatic.dm
- code/modules/projectiles/guns/projectile/mattguns.dm
- code/modules/projectiles/guns/projectile/pistol.dm
- code/modules/projectiles/guns/projectile/shotgun.dm
- code/modules/projectiles/guns/projectile/sniper.dm
- code/modules/projectiles/projectile/bullets.dm
- code/modules/projectiles/projectile/energy.dm
- code/modules/projectiles/projectile/special.dm
- code/modules/research/designs.dm
Weapon related movement slowdown is a bit more balanced. Added delay to a lot more weapons. You'll notice for now that melee weapons don't have slowdown and that's because I've yet to start adding slowdown to heavy melee weapons yet, though even if I do -- it's likely only going to effect very heavy weapons like the Daemonhammer or Chainsword.
Removed old useless move_delay code.
Backpacks in general have +4 added to space.
Disabled invisibility ring.
Holsters can now only contain small items such as knives, cutro blades, pistols -- etc. The seolite plasma pistol is uniquely the only plasma pistol that can be held within a holster, as it is canon considered a small sized plasma weapon.
Fixed up explosion code for a number of ranged weapons, along with fire_delay.
Astares ammo and boltgun …
> Guns, Holsters, Backpacks and Boomies

- code/game/jobs/job/adeptus_ministorum.dm
- code/game/jobs/job/inquisition.dm
- code/game/jobs/job/warhammer_jobs.dm
- code/game/objects/items/weapons/swords_axes_etc.dm
- code/modules/clothing/suits/armor.dm
- maps/delta/warhammer-2.dmm
Since nobody was playing progena, I've replaced them with novitiate sisters. Players can pick to be either militant or hospitaller novitiates 
This has been done to both fit more with the newer lore and also to increase church player count. People don't really play ministorum roles unless they're Adepta Sororitas roles, and absolutely nobody was playing progena. 
Should not hurt game balance. Novitiate armor stats are pretty abysmal. They do not have proper power armor and have stats similar to guardsmen if they are militants.
Map changes are purely spawn changes to make sure novitiates spawn in their room as well as adding a skull and a candle to the deacon's office because it looks rad.
There was an inquisition helmet causing an error which has now been removed.
> Removes Progena, replaces with Novitiate

- code/game/jobs/job/adeptus_ministorum.dm
- code/game/jobs/job/pilgrims.dm
Gives witchhunter a simple laspistol and holster.
Gives Noviates their headwear, it was forgotten oversight.
> Small church fix.

- code/datums/outfits/jobs/medical.dm
- code/game/jobs/job/adeptus_ministorum.dm
- code/game/jobs/job/inquisition.dm
- code/game/objects/effects/landmarks.dm
- code/game/objects/items/devices/mechanicustoys.dm
- code/game/objects/items/weapons/baton.dm
- code/game/objects/items/weapons/cane.dm
- code/game/objects/items/weapons/material/swords.dm
- code/game/objects/items/weapons/melee/energy.dm
- code/game/objects/items/weapons/melee/misc.dm
- code/game/objects/items/weapons/storage/backpack.dm
- code/game/objects/items/weapons/stunbaton.dm
- code/game/objects/items/weapons/swords_axes_etc.dm
- code/game/objects/items/weapons/weaponry.dm
- code/game/objects/newmap/dungeon_code.dm
- code/modules/clothing/suits/armor.dm
- code/modules/clothing/suits/astartes.dm
- code/modules/cultist/components/hereticitem.dm
- code/modules/cultist/deities.dm
- code/modules/cultist/runes/tzeentch.dm
- code/modules/library/manuals/manuals.dm
- code/modules/mob/living/carbon/human/unarmed_attack.dm
- code/modules/mob/mob_helpers.dm
- code/modules/projectiles/guns/projectile/mattguns.dm
- code/modules/projectiles/guns/projectile/sniper.dm
- code/modules/projectiles/projectile/beams.dm
- code/modules/projectiles/projectile/bullets.dm
- code/modules/projectiles/projectile/energy.dm
- code/modules/projectiles/projectile/magnetic.dm
- code/modules/projectiles/projectile/special.dm
Will add changelog later.
TL;DR
Inquisitorial/Primer/Ecclesiarchy books kind of in(not working). Looks cool though.
Added new satchel code that creates slowdown, with a lightweight and heavy satchel. Magos/Priest and Power Packs immune.
Fixed melee code to now penetrate armor, with various 'tiers' on what melee weapons penetrate what armor. Emphasizing their strengths and weaknesses. 
Fixed astartes power armor and sisters, also gave Astartes better protection against damage so you need specialized weapons like sniper rifles, or kraken penetrator shotgun slugs to hurt them. 
Re-did AP on all ranged weapons too. I worked off 40k logic, being that some not all autoguns penetrate imperial flak armor. For example pistols will do fuck all to imperial flak, but revolvers have a chance to …
> Temp Big Update

- code/game/mecha/mecha.dm
This was "fixed" because of a mixture of complaints, copium and also hearing tales of people using this to abuse the tau mechs. It's a simple "fix" that takes 2 seconds to do. Seemed to work when I tried it on local. So.... I hope this doesn't cause issues B)
Literally just stops being being able to force eject people from mechs without being inside them. Force eject is supposed to be internal only from what I can see, that or an external ejection but it takes time. Yada Yada funny moment.
> "Fixes" force eject

- code/modules/cultist/runes/nurgle.dm
Someone made the offer_brain ritual send to Khorne instead of Nurgle. Brains will now give favor as intended. Also buffs favor slightly, to put it on level with Khorne.
> Fixes nurgle ritual again (real)

- code/modules/admin/admin.dm
- code/modules/admin/admin_verbs.dm
- code/modules/admin/verbs/randomverbs.dm
Adds a function to then remove roles from in-round. Contrary to popular belief, admins before could NOT remove roles, only add. (That wont go poorly right?)
Allows for admins to run faction focused events (Disabling roles to balance it out) also allowing them to test things based on role count (removing/adding roles to test). This will also allow for roles to be removed if one is added by accident. 
So far it seems to work, also fixed my issue with localhosting so I was able to test it and it appeared to run well.
Oprime has indeed helped with making this and keeping it functional so that's epic, thank the big man for the help to let this go faster B)
> Fixes admin role add/remove function (admins can now add/remove roles!)

- code/modules/research/designs.dm
Fixed armor production - it should be able to produced through the Protolathe, as soon as the necessary tech levels are met. It will also highlight which items are armor, as per standard notation so far. Can switch it to the Auto
This should make the AdMech much more of a supply-and-support faction.
> Protolathe Armor Production Update designs.dm

- code/modules/mob/living/carbon/human/species/races/orks/ork_species.dm
Ork Brain Health lowered even more so they die ever faster now.
Their brute modifier is 0.72 from 0.75
Laser modifier is 0.76 from 0.75
What this means is burns hurt them more then bullets which is just ork physiology. You can shoot them with regular bullets and it mostly just stings, but bolter rounds, lasguns and flamers are the only real threats to an Ork outside of a bullet to the brain.
> Ork Balance

- code/modules/clothing/rings/rings.dm
Makes the code safer, and makes it easier to use the ring. It now activates on equip.
> fixes halo ring

- code/game/jobs/job/astra_militarum.dm
- code/game/jobs/job/pilgrims.dm
- code/game/objects/items/weapons/explosives.dm
- code/modules/mining/mine_items.dm
- maps/delta/warhammer-1.dmm
- maps/delta/warhammer-2.dmm
- maps/delta/warhammer-4.dmm
- maps/delta/warhammer-5.dmm
- maps/delta/warhammer-7.dmm
Minor Mapping QOL -- major changes is just the spawners for guard and armory edits.
Guard returned to game but reduced slots.
Plastique explosives renamed to canon name Det Packs. Will be also making a grenade version of the det pack in future. This one is called det pack - breacher
Mining Items have added Armor_Penetration, Pilgrim Miners now start with upgraded pickaxes that double as decent weapons.
Fixed up Pilgrim Equip code slightly so their outfits attached to their bodies instead of dropping on the floor.
Made Tavern Keeper human.
Guard Command structure is now basically - everyone answers to PDF Captain or Commissar, but Captain first.
> Guard Return + QOL

- code/modules/mob/living/carbon/human/species/races/krootboys.dm
- code/modules/organs/internal/eyes.dm
- Gives Kroot species specific eyes which grant IR sight (essentially mesons. Cannot see objects)
Kroot in lore have eyes which can see into the IR spectrum and visualize the body heat of prey. This reflects that mechanically
- Gives Kroot the bladderless trait by default
Kroot in lore do not defecate/urinate. They instead sweat out their waste/excrement. This reflects that mechanically
> Kroot biology lore additions
