WoodenTucker/40K-Eipharius

- code/modules/mob/living/silicon/say.dm
- code/modules/mob/say.dm
- interface/skin.dmf
Reverts WoodenTucker/40K-Eipharius#2
> Revert "Noble's hotkey change, removal"

- code/modules/mob/living/silicon/say.dm
- code/modules/mob/say.dm
- interface/skin.dmf
Reverts WoodenTucker/40K-Eipharius#3
> Revert "Revert "Noble's hotkey change, removal""

- code/game/objects/items/trash.dm
- code/modules/food/recipes_microwave.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
- code/modules/reagents/reagent_containers/food/snacks.dm
Added some food and drinks. Triglyceride Gel is basically Liquidfood MRE, but for Astartes.
> Dmitrov's Cuisine: Part 1

- code/game/machinery/computer/welcargo.dm
- code/modules/reagents/reagent_containers/food/drinks/bottle.dm
Added Caddisian Wine to Munitorum. Really expensive.
> Dmitrov's Cuisine: Part 1.5 - Caddisian Wine Bottles at Munitorum

- code/datums/outfits/jobs/engineering.dm
- code/game/objects/items/devices/mechanicustoys.dm
- code/game/objects/items/weapons/storage/backpack.dm
> Omnissiah axe

- code/game/jobs/job/adeptus_mechanicus.dm
im almost sure that nothing here will break
> Tech priest surgery skill fix

- code/game/machinery/computer/computer.dm
- code/game/machinery/supplybeacon.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
- code/modules/reagents/reagent_containers/food/drinks/bottle.dm
- maps/delta/warhammer-4.dmm
- maps/delta/warhammer-5.dmm
- maps/delta/warhammer_areas.dm
- maps/delta/warhammer_shuttles.dm
Check commits for the description.
> Mapping Update, Dmitrov's Cuisine, Minor Fixes

- code/datums/supplypacks/hospitality.dm
- code/game/objects/items/weapons/clothingbag.dm
- code/game/objects/random/random.dm
- code/modules/clothing/glasses/glasses.dm
- code/modules/clothing/head/astartes.dm
- code/modules/clothing/masks/gasmask.dm
- code/modules/clothing/masks/miscellaneous.dm
- code/modules/clothing/shoes/jobs.dm
- code/modules/clothing/shoes/miscellaneous.dm
- code/modules/clothing/suits/astartes.dm
- code/modules/clothing/under/miscellaneous.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
- maps/delta/jobs/astarte.dm
- maps/delta/outfits/astartes.dm
- maps/delta/warhammer-1.dmm
Fucking MASSIVE clothing update, including outfits. and also a minor fix of poisonberry juice.
> Major Clothing Update

- code/game/objects/auras/aura.dm
- code/modules/mob/living/carbon/human/species/races/astartes.dm
- code/modules/mob/living/carbon/human/species/species.dm
ok im almost sure that this will work, butttttt, this is my first time doing branch stuff
> [Shitcode] Gives astartes regeneration

- code/modules/surgery/encased.dm
- code/modules/surgery/generic.dm
- code/modules/surgery/organs_internal.dm
> Ghetto surgery options

- code/modules/surgery/encased.dm
forgot the \
i doubt that this was going to break anything or something like that, but it adds polish to the shitcode
> forgot the \

- code/game/jobs/job/astra_militarum.dm
- maps/delta/outfits/guardsmen.dm
i am CLEARLY forgetting something, russian.
> Job alt title

- code/game/jobs/job/astra_militarum.dm
- maps/delta/outfits/guardsmen.dm
Reverts WoodenTucker/40K-Eipharius#36
> Revert "Job alt title"

- code/game/jobs/job/astra_militarum.dm
- maps/delta/outfits/guardsmen.dm
Reverts WoodenTucker/40K-Eipharius#38
> Revert "Revert "Job alt title""

- code/game/jobs/job/astra_militarum.dm
- maps/delta/outfits/guardsmen.dm
Reverts WoodenTucker/40K-Eipharius#39
> Revert "Revert "Revert "Job alt title"""

- code/game/jobs/job/adeptus_astartes.dm
Fixed the Astartes, going to try Militarum
> Astartes Chapter Selection Fix

- code/game/jobs/job/adeptus_astartes.dm
- code/game/jobs/job/astra_militarum.dm
- maps/delta/outfits/astartes.dm
Spacemarines now select their chapter from character setup and get skill boosts depending on chapter. Guardsmen were a bit fucked, so fixed them by reverting them back, going to deal with their jobs later.
> Astartes Job Titles

- code/game/jobs/job/adeptus_astartes.dm
- code/game/jobs/job/astra_militarum.dm
- maps/battle/jobs/astarte.dm
- maps/delta/outfits/astartes.dm
> Fix Attempt

- code/game/objects/items/weapons/melee/misc.dm
the only way to get slanpain before  was the mutated arm, which you needed 200(+20 to toggle it) pain to get to, i do not know when this was broken, but someone broke it and this is the fix for it.
NOTE:nerfed force from 45 to 30
NOTE: copy pasted this shit from slaanesh arm here
> BUG FIX: FIXES LASH OF TORMENT

- code/game/jobs/job/SS13/security.dm
- code/game/jobs/job/adeptus_astartes.dm
- code/game/objects/items/weapons/melee/misc.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
- code/modules/reagents/Chemistry-Recipes.dm
- maps/delta/jobs/astarte.dm
- maps/delta/warhammer_areas.dm
- maps/delta/warhammer_define.dm
Just fixed a bit of code to ensure stability and probably prevent some bugs.
> Minor patch

- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
this probably should work
NOTE:removed the ability of liquid(now dust) phoron to turn into atmos phoron just by being splashed on the floor
> renames reagent phoron to promethium

- code/modules/materials/materials.dm
> crystal promethium

- code/game/jobs/job/inquisition.dm
- code/modules/projectiles/guns/flamer.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
- code/modules/reagents/Chemistry-Recipes.dm
Flamer finally works as should work, without igniting the owner.
> Major Flamer Fix

- code/datums/outfits/jobs/command.dm
- code/game/jobs/job/astra_militarum.dm
- code/modules/clothing/shoes/jobs.dm
- maps/battle/outfits/guardsmen.dm
- maps/delta/outfits/guardsmen.dm
> "ey mate, got a knuife" fix

- code/modules/mob/living/carbon/human/species/races/krootboys.dm
- code/modules/mob/living/carbon/human/species/races/orks/ork_species.dm
- code/modules/mob/living/carbon/human/species/races/tau.dm
> Funny latepartye

- code/game/objects/items/devices/mechanicustoys.dm
> attempted fix numba 1

- maps/delta/warhammer-2.dmm
> removes "command boots" FROM THE OTHER MAP TOO
> i frogot, again

- code/datums/outfits/jobs/science.dm
- code/game/jobs/job/adeptus_mechanicus.dm
- code/game/jobs/job/astra_militarum.dm
- code/game/objects/items/weapons/cards_ids.dm
- code/modules/mob/living/carbon/human/species/station/station.dm
- maps/delta/jobs/warhammer_jobs.dm
i don't even know what the fuck happened, you haven't seen the horrors that i have seen, but anyway, i have fixed all the shitcode that i made but its still buggy as fuck so yeah,
fixed a buggy mess of the xenobiologist role(defunct but still, i chose to try to mess around with it so any future coders knew that it wasn't meant to exist) 
fixed some descriptions
fixed some skills and shit
mixed magos and biologis access, both have ALMOST the same access, with biologis having less access due to not being the current leader of the mechanicus but still being a magi
> THE HORRORS OH THE HORRORS

- maps/delta/warhammer-1.dmm
This is a merge of my map from the other project.
Basically just adds the finishing touches to the dungeon, this was done literally in 2021 but never got patched in. So I just franksteined this bitch to the current map.
ADDITIONS
Sewer System.
Extended Slums & City Outskirts
Mines Area(Lots of lore & daemons to duke it out with.)
REMOVED
A few items.
Handful of daemons(Certain mobs would wander to the entrance of the dungeon. I don't like the idea of players dying before they even get inside the place, you should be able to step your foot in the door and THEN die.)
TIPS
If you are new to the dungeon, make sure you bring buddies. Understand the daemons move around a lot so they'll bump into you, if you want to roleplay or heal up. Find a place you can HIDE so you don't get your arms ripped …
> Update to DUNGEON

- code/datums/outfits/jobs/medical.dm
- code/game/jobs/job/adeptus_astartes.dm
- code/modules/clothing/glasses/glasses.dm
adds Health HUDs to most medical roles(includes alchemist)
fixes spiss marines HUD and gives them a sprite, i think that they will be working now.
fixes spiss marines skillset by generalizing them, its not good, but its either this or ask cain to fix what he created
spess marine integrated shitter
> FIXES SOME SHITTE

- code/game/jobs/job/astra_militarum.dm
- code/game/objects/items/devices/mechanicustoys.dm
- code/modules/clothing/glasses/glasses.dm
- code/modules/mining/ingotcrafting.dm
- code/modules/projectiles/ammunition/boxes.dm
- code/modules/projectiles/ammunition/bullets.dm
- code/modules/projectiles/guns/energy/laser.dm
- code/modules/projectiles/guns/projectile/mattguns.dm
- code/modules/projectiles/guns/projectile/pistol.dm
- code/modules/projectiles/guns/projectile/shotgun.dm
- code/modules/projectiles/projectile/bullets.dm
- code/modules/projectiles/projectile/energy.dm
- maps/battle/outfits/astartes.dm
- maps/delta/outfits/astartes.dm
- maps/delta/outfits/guardsmen.dm
> meltagun is added and funcional, it is pretty weak still
> nerfed like two weapons
> made all astartes bolter rifles /bolter/ instead of /bolterbang /smurfbolter etc
> added the basics of meltagun
> added the basics of Metal Storm Bolter ammo, still not working
> added Kraken Penetrator ammo, made using adamantium
> added the basics of the lascannon
> i have a ton of ideas that i will forget in two hours
> added the BASICS of the handflamer
> forgot to balance normal flamer
> New weapons and shit

- code/game/jobs/job/astra_militarum.dm
- code/game/objects/items/devices/mechanicustoys.dm
- code/modules/clothing/glasses/glasses.dm
- code/modules/mining/ingotcrafting.dm
- code/modules/projectiles/ammunition/boxes.dm
- code/modules/projectiles/ammunition/bullets.dm
- code/modules/projectiles/guns/energy/laser.dm
- code/modules/projectiles/guns/projectile/mattguns.dm
- code/modules/projectiles/guns/projectile/pistol.dm
- code/modules/projectiles/guns/projectile/shotgun.dm
- code/modules/projectiles/projectile/bullets.dm
- code/modules/projectiles/projectile/energy.dm
- maps/battle/outfits/astartes.dm
- maps/delta/outfits/astartes.dm
- maps/delta/outfits/guardsmen.dm
reverts and fixes the revert of my PR
> Revert 82 revert 81 new weapons and shit

- code/game/jobs/adeptus_ministorum.dm
- code/game/jobs/astra_militarum.dm
- code/game/jobs/job/inquisition.dm
- code/game/jobs/job/rogue_traders.dm
- maps/battle/jobs/guardsmen.dm
Small fixes. Very important.
Job fixes, no more Chaos Guardsmen or Ordos Hospitaller.
Also Acolyte/Inquisitor fixed.
> Ravenor 0.21

- code/modules/projectiles/guns/energy/laser.dm
- code/modules/projectiles/projectile/energy.dm
- maps/delta/outfits/inquisition.dm
Added hotshot lasguns, their projectiles, and gave them to acolytes. Now you can spawn in Tempestus Scions and give them all the cool equipment.
> Hotshot lasguns.

- code/modules/clothing/head/astartes.dm
- code/modules/clothing/head/hardhat.dm
Reverts WoodenTucker/40K-Eipharius#89
> Revert "last fix"

- code/game/jobs/job/astra_militarum.dm
> Missing File

- code/game/objects/items/weapons/cane.dm
- code/game/objects/items/weapons/material/misc.dm
- code/game/objects/items/weapons/material/swords.dm
- code/game/objects/items/weapons/melee/misc.dm
- code/game/objects/items/weapons/swords_axes_etc.dm
- code/modules/projectiles/guns/energy/laser.dm
- code/modules/projectiles/guns/projectile/automatic.dm
- code/modules/projectiles/guns/projectile/mattguns.dm
- code/modules/projectiles/guns/projectile/pistol.dm
- code/modules/projectiles/guns/projectile/revolver.dm
- code/modules/projectiles/guns/projectile/shotgun.dm
- code/modules/projectiles/guns/projectile/sniper.dm
- code/modules/projectiles/projectile/bullets.dm
"balancecode time update" update:
- possibly fixed lasguns keeping their hotshot values(depending on your firemode your lasgun now will change the energy cost)
- fixed most shotguns and guns in general
- put warning labels on guns that shouldn't be in game
- first step of balancing all BALLISTIC guns
- changed the snipers(lasgun, needler and scoped boscolet) folder to be on the sniper folder
- changed buckshot from 8 times 40 damage to 8 times 20 damage
- changed boltpistol damage, now its 55 damage, 40 bullet penetration, one shot isn't cool, neither is weak garbage, so yeah, this should be balanced
- changed bolter damage, now its 65, 50 bullet penetration
- buffed scrapmace damage, its 40 now instead of 30
"NO CHANCE DUDE" update:
- changed trench axe block chance from 30 to 50
- …
> updates and shit

- code/modules/mining/ingotcrafting.dm
- maps/warhammer/jobs/pilgrims.dm
For some reasons pilgrim file changes doesn't looks correctly and actually haves few strings of changes instead of whole file
> Ingot crafts + Pilgrims non-random fates

- code/game/jobs/adeptus_ministorum.dm
- code/game/jobs/astra_militarum.dm
- code/game/jobs/job/adeptus_mechanicus.dm
- code/game/jobs/job/adeptus_ministorum.dm
- code/game/jobs/job/astra_militarum.dm
- code/game/jobs/job/civilian.dm
- code/game/jobs/job/departmento_munitorum.dm
- code/game/jobs/job/job.dm
- code/modules/mob/datum_stats_skills.dm
- code/modules/mob/living/carbon/human/human_attackhand.dm
- code/modules/mob/living/carbon/human/human_defense.dm
- code/modules/mob/living/carbon/human/species/races/nids.dm
- code/modules/mob/living/carbon/human/species/races/orks/abilities.dm
- maps/battle/jobs/pilgrims.dm
- maps/delta/jobs/pilgrims.dm
If melee ever breaks again do refer to this PR to know what files effect melee - it references all characters that use melee as a skill outside of species.
It also touches on Dexterity for all species(Except Tau).
You'll notice the critical failure stuff is disabled also.
> Melee Fix Update

- code/game/jobs/job/inquisition.dm
- code/game/objects/auras/aura.dm
- code/modules/mob/living/carbon/human/species/races/astartes.dm
- code/modules/mob/living/carbon/human/species/races/nids.dm
- code/modules/mob/living/carbon/human/species/races/orks/abilities.dm
- code/modules/mob/living/carbon/human/species/races/orks/ork_species.dm
- code/modules/mob/living/carbon/human/unarmed_attack.dm
- maps/delta/warhammer-2.dmm
Read the comments for information on this update you mongus.
Touches on Orkz and Tyranids primarily.
> Minor Update - Ravenor

- code/modules/mob/living/carbon/human/species/races/orks/ork_species.dm
Revert this if it doesn't work. Small tweaks to Orks.
Removed pain immunity since Orks don't fall over until the very moment they die which takes forever.
Increase their passive regen / HP as a result.
> Orkz Update

- code/_global_vars/misc.dm
- code/modules/admin/admin_verbs.dm
- code/modules/mob/observer/lateparty.dm
This PR is a rework of the existing late party system. It now allows players to queue as a group and eventually spawn as one instead of coming in one at a time. 
I tested it a bit and it seems to work fine, please let me know any issues.
ADMINS:
There is now a new verb called Choose Party Size in the fun tab. Like other party verbs, this lets you choose the queue size for the party. The default is 4 and can be scaled to 10.
> Group late parties and party size verb

- code/modules/admin/admin_verbs.dm
Reverts WoodenTucker/40K-Eipharius#123
> Revert "Adds 2 option to party"

- code/_global_vars/misc.dm
- code/modules/admin/admin_verbs.dm
- code/modules/mob/observer/lateparty.dm
Reverts WoodenTucker/40K-Eipharius#118
> Revert "Group late parties and party size verb"

- code/game/items/weapons/torturetools.dm
- code/game/jobs/job/adeptus_mechanicus.dm
- code/game/objects/items/weapons/cane.dm
- code/modules/mob/living/say.dm
- config/in_character_filter.txt
- maps/delta/outfits/astartes.dm
- maps/delta/outfits/inquisition.dm
massively buffs mechanicus endurance stat, they arent supposed to feel pain but they still do, so this should help against them being unable to walk after being shot once.
gives mechanicus better weapons and melee skills
makes it so mechanicus strength and dext can range from 15 to 18 (magos 18 to 20) due to their heavy modifications, i think i made it so biologis can be 
gives raven techmarine shoes
gives all inquisition members NVGs
updates censored words(removes a lot of them)
updates the word modifier, if someone says a bad word it may be changed to... something more spicy, for example if you say GLORY TO KHORNE! i mean, the N word, you will instead say GLORY TO KHORNE, but if you say the other N Word it will just be turned into Homie
fixes ravenor's code
> Minor bugfixes + balances mechanicus a bit more

- maps/delta/outfits/inquisition.dm
Not a compile error but I realize in my update I wrote the same line twice for inventory, which might mean Malleus Interrogator's accidentally spawn with two guns.
> Inquisition Outfit Fix

- code/game/gamemodes/warfare/turfs.dm
- code/game/jobs/astra_militarum.dm
- code/game/jobs/job/astra_militarum.dm
- code/game/objects/items/weapons/stunbaton.dm
- code/modules/clothing/suits/armor.dm
- code/modules/mob/living/carbon/human/species/races/nids.dm
- maps/delta/jobs/warhammer_jobs.dm
- turfs.dm
Trying out some balancing stuff on the Nids and also fixed them freezing in cold environments which made them slow.
The guard slots being reduced by 2 is important since I want to honestly see what happens if we reduce Guard counts and start relying on Pilgrim roles like Enforcer or Mercenary Characters to patrol the town. The guard do quite a lot of  everything right now, also the Commissar spawn text being added should discourage people from forcing folks to sit in trenches all round.
It's getting really boring and these are changes we'll need to encourage especially moving into Hive City Map which won't work if people play it like a trench simulator too.
> Minor Tweaks to Nids/Guard

- code/game/machinery/computer/welcargo.dm
- code/game/objects/effects/landmarks.dm
- code/modules/mob/living/carbon/human/life.dm
- maps/delta/outfits/guardsmen.dm
Removes Grim Autogun from spawning until the magazines function.
> Autogun Fix

- maps/delta/jobs/warhammer_jobs.dm
The sister hospitaller was accidentally disabled with a commenting error in a previous PR of mine. Now returned.
> Sister Return!

- maps/delta/jobs/warhammer_jobs.dm
Reverts WoodenTucker/40K-Eipharius#151
> Revert "Sister Return!"

- code/datums/outfits/jobs/engineering.dm
- code/datums/outfits/jobs/medical.dm
- code/game/jobs/job/adeptus_mechanicus.dm
- code/game/jobs/job/adeptus_ministorum.dm
- code/game/objects/items/devices/mechanicustoys.dm
- code/modules/clothing/glasses/glasses.dm
- code/modules/clothing/gloves/miscellaneous.dm
- code/modules/clothing/shoes/jobs.dm
- code/modules/organs/external/standard.dm
- maps/delta/outfits/astartes.dm
- maps/delta/outfits/inquisition.dm
alright a lot of stuff is fixed byeee
> fixes a fuckload of shit

- code/game/jobs/cults/tzeentch.dm
- code/game/jobs/job/astra_militarum.dm
Commissar fix and Tzeentch bit expansion
> Merge fast: little, but necessary bugfix

- code/modules/organs/organ.dm
Seemingly reduces lag spike by 40x. Still pauses the server for about a second or two.
> Relief to head cannibalism

- code/game/objects/items/devices/mechanicustoys.dm
someone that i won't mention made it able to be infinitely droppable and also made it so it was a blunt object.
> fixes power axe

- code/game/objects/items/devices/mechanicustoys.dm
Reverts WoodenTucker/40K-Eipharius#188
> Revert "fixes power axe"

- code/modules/mob/living/carbon/human/death.dm
- code/modules/mob/living/carbon/human/human_defines.dm
- code/modules/mob/living/carbon/human/human_organs.dm
- code/procs/statistics.dm
[Comp proof](https://i.gyazo.com/43b377703dbd332b501613f5969ae658.png)
Very barebones, may need to tweak I'm not sure if sql can handle parameters thru byond, we shall see
> Rudimentary played time tracking

- code/modules/mob/living/carbon/human/human_defense.dm
Good armor should now be far more likely to deflect projectiles. Whereas, previously even when your damage was negative, you always had a chance of having an artery severed. The odds for that should be lower. This also increases the chance of organs being hit by projectiles based on damage, and increases the damage done. Which should make orks more mortal.
> Armor penetration changes

- code/game/jobs/job/pilgrims.dm
> Fixes two job skills

- code/game/jobs/cults/ruinouspowers.dm
> Fixes cult status icons

- code/game/jobs/cults/ruinouspowers.dm
> Fix cult icon v2

- code/modules/mob/living/carbon/human/human_defense.dm
Reverts WoodenTucker/40K-Eipharius#200
> Revert "Armor penetration changes"

- code/game/jobs/cults/ruinouspowers.dm
> Actually fixes cult

- code/modules/mob/living/carbon/human/human_defense.dm
> Uses armor check to calculate armor penetration

- IS12Warfare.dme
> Removes deathstalker include

- code/game/objects/items/stacks/medical.dm
- code/modules/mob/living/carbon/human/human_defense.dm
- code/modules/projectiles/projectile_new.dm
- code/modules/reagents/reagent_containers.dm
- code/modules/reagents/reagent_containers/food/snacks.dm
- code/modules/surgery/suture_wound.dm
- code/procs/statistics.dm
No more negative or positive effects from interacting with already dead children
> Adds  checks if dead for parental vice

- code/modules/projectiles/projectile/bullets.dm
- code/modules/projectiles/projectile/energy.dm
- code/modules/projectiles/projectile/special.dm
Testing a bullet update today for the server, feel free to record any notes on specific weapon balances. I want to get our balance correct on bullets, there's been complaints for weeks and I think now is a good time to take a good crack at making ranged combat satisfying.
This update is also going to be coupled with ZAB's mattguns update which will touch stubbers with further changes. Munitions variants will also be added later.
> Bullet Update

- code/modules/client/preference_setup/general/03_body.dm
- code/modules/cultist/deity.dm
- code/modules/cultist/rune.dm
- code/modules/cultist/runes/khorne.dm
- code/modules/cultist/runes/nurgle.dm
- code/modules/cultist/runes/slaanesh.dm
- code/modules/cultist/runes/tzeentch.dm
- code/modules/mob/shit_piss.dm
- code/modules/reagents/reagent_containers/pill.dm
Cults should properly display for everyone, fixes some type path errors, maybe fixes conversion.
> Cult fixes

- code/controllers/subsystems/jobs.dm
Now tells the user when it fails to add them on roundstart
> Further cult change

- code/game/antagonist/outsider/ert.dm
- code/game/jobs/job/adeptus_mechanicus.dm
- code/game/objects/items/devices/mechanicustoys.dm
- code/modules/mob/living/carbon/human/species/station/skitarii.dm
- code/modules/projectiles/ammunition/boxes.dm
- code/modules/projectiles/ammunition/bullets.dm
- code/modules/projectiles/guns/projectile/mattguns.dm
- code/modules/projectiles/projectile/bullets.dm
Added in Galvanic rifles, ammo, magazines, and more, and gave to Skitarii (With ammo). New mechanicus equipment, and outfits for the ERTs have been fixed.
> Mechanicus toys and ERT equipment.

- code/controllers/subsystems/gods.dm
- code/game/objects/items/weapons/soap.dm
- code/modules/cultist/deities.dm
- code/modules/cultist/deity.dm
- code/modules/cultist/effects/khorne.dm
- code/modules/cultist/rune.dm
- code/modules/cultist/runes/illusion.dm
- code/modules/cultist/runes/khorne.dm
- code/modules/cultist/runes/nurgle.dm
- code/modules/cultist/runes/rune_types.dm
- code/modules/cultist/runes/slaanesh.dm
- code/modules/cultist/runes/tzeentch.dm
> Fixes khorne, cleans up cult code a little

- code/game/antagonist/outsider/ert.dm
- code/game/jobs/job/adeptus_mechanicus.dm
- code/game/objects/items/devices/mechanicustoys.dm
- code/modules/mob/living/carbon/human/species/station/skitarii.dm
- code/modules/projectiles/ammunition/boxes.dm
- code/modules/projectiles/ammunition/bullets.dm
- code/modules/projectiles/guns/projectile/mattguns.dm
- code/modules/projectiles/projectile/bullets.dm
All working well now, merging should be fine.
> Previous PR with conflict issues now resolved.

- code/modules/mob/living/simple_animal/simple_animal.dm
Fixed up the AI, they had their brain power reduced by 5. They can now do intelligent things.
> AI Dun Heccin Fixed

- code/modules/admin/admin.dm
- code/modules/admin/topic.dm
- code/modules/mob/living/carbon/carbon_needs.dm
- code/modules/mob/living/carbon/human/vice.dm
Small fixes here
Mentors have been corrected and added, for posterity's sake I also added the new trialmins on the server.
I have added additional vice warnings into the game that will proc passively and warn you of your increasing need. I have also displayed the amount ingame through clicking your doll. 
Admins and mentors: 
No longer must you answer dumb IC questions next to all ahelps you will notice a new FOIG button.
This will send a message to the player to find out in-game along with a nice spooky noise.
Comp proof:
Next up, piety eucharist
> Mentor fix, FOIG addition, small vice changes

- code/game/items/weapons/torturetools.dm
> torture tools fixed

- code/datums/outfits/jobs/science.dm
- code/game/jobs/job/adeptus_mechanicus.dm
- code/game/objects/items/weapons/storage/backpack.dm
- code/modules/clothing/glasses/glasses.dm
- code/modules/clothing/shoes/jobs.dm
- code/modules/clothing/suits/armor.dm
- code/modules/clothing/suits/toggles.dm
- code/modules/mining/ingotcrafting.dm
- code/modules/mob/living/carbon/human/species/station/skitarii.dm
- code/modules/projectiles/ammunition/boxes.dm
- code/modules/projectiles/ammunition/bullets.dm
- code/modules/projectiles/guns/energy/special.dm
- code/modules/projectiles/guns/projectile/mattguns.dm
- code/modules/projectiles/projectile/bullets.dm
- code/modules/projectiles/projectile/special.dm
Added a lot of new stuff for the Mechanicus, including two new kinds of Skitarii (Custom sprites pending), an Explorator role, Rad Carbines, Rad Pistols, and a Phosphor Pistol.
> Mechanicus updates!

- code/modules/cultist/deities.dm
- code/modules/cultist/effects/nurgle.dm
Reverts WoodenTucker/40K-Eipharius#281
> Revert "Nurgle abilities"

- code/modules/cultist/deities.dm
- code/modules/cultist/effects/nurgle.dm
Reverts WoodenTucker/40K-Eipharius#285
> Revert "Revert "Nurgle abilities""

- code/modules/mob/living/carbon/carbon_powers.dm
- code/modules/mob/living/carbon/human/species/races/nids.dm
- code/modules/mob/living/simple_animal/borer/borer.dm
- code/modules/mob/living/simple_animal/borer/borer_powers.dm
- code/modules/spells/aoe_turf/knock.dm
- code/modules/spells/general/radiant_aura.dm
Added in new Tyranid selection system with Zoanthropes, updated stats, and completely reworked Borers.
> Borer changes and Zoanthrope addition.

- code/modules/mob/living/carbon/carbon_powers.dm
- code/modules/mob/living/carbon/human/species/races/nids.dm
- code/modules/mob/living/simple_animal/borer/borer.dm
- code/modules/mob/living/simple_animal/borer/borer_powers.dm
- code/modules/spells/aoe_turf/knock.dm
- code/modules/spells/general/radiant_aura.dm
Reverts WoodenTucker/40K-Eipharius#325
> Revert "Borer changes and Zoanthrope addition."

- code/game/objects/items/weapons/cards_ids.dm
- code/game/objects/items/weapons/material/misc.dm
- code/game/objects/items/weapons/melee/misc.dm
- code/modules/clothing/suits/armor.dm
Does not require compile test as it's editing sales price values on existing items. Fast-merging.
> Price Edit

- code/modules/mob/living/carbon/carbon_powers.dm
- code/modules/mob/living/carbon/human/species/races/nids.dm
- code/modules/mob/living/simple_animal/borer/borer.dm
- code/modules/mob/living/simple_animal/borer/borer_powers.dm
- code/modules/spells/aoe_turf/knock.dm
- code/modules/spells/general/radiant_aura.dm
Reverts WoodenTucker/40K-Eipharius#326
> Revert "Revert "Borer changes and Zoanthrope addition.""

- code/modules/mob/living/carbon/carbon_powers.dm
- code/modules/mob/living/carbon/human/species/races/nids.dm
- code/modules/mob/living/simple_animal/borer/borer.dm
- code/modules/mob/living/simple_animal/borer/borer_powers.dm
- code/modules/spells/aoe_turf/knock.dm
- code/modules/spells/general/radiant_aura.dm
Reverts WoodenTucker/40K-Eipharius#342
> Revert "Revert "Revert "Borer changes and Zoanthrope addition."""

- code/modules/cultist/runes/khorne.dm
- code/modules/cultist/runes/nurgle.dm
- code/modules/cultist/runes/slaanesh.dm
- code/modules/cultist/runes/tzeentch.dm
90% chance this fixes it. Improper override.
> Fixes conversion

- code/modules/mob/living/carbon/human/species/races/nids.dm
- code/modules/projectiles/guns/projectile/mortar.dm
Tyranids are restored. 
Mortar functions.
> Fix Nids + Mortar

- code/game/objects/effects/landmarks.dm
- code/game/objects/items/toys.dm
- code/game/objects/items/weapons/material/swords.dm
- code/modules/cargo/categories/melee.dm
- code/modules/mob/living/simple_animal/hostile/smalldemon.dm
- maps/delta/warhammer-1.dmm
Added Adamantine Variants of certain melee weapons. Will do more variations of melee and also guns later.
Fix to some melee stats.
Edits to demons to be less OP.
Fixed up the clinic in Delta 1 having no power.
Edited landmarks to include new variants.
> Minor Edits

- code/game/jobs/job/adeptus_astartes.dm
- code/game/jobs/job/adeptus_mechanicus.dm
- code/game/jobs/job/adeptus_ministorum.dm
- code/game/jobs/job/astra_militarum.dm
- code/game/jobs/job/civilian.dm
- code/game/jobs/job/departmento_munitorum.dm
- code/game/jobs/job/inquisition.dm
- code/game/jobs/job/magistratum.dm
- code/game/jobs/job/pilgrims.dm
- code/game/jobs/job/rogue_traders.dm
- code/modules/mob/living/carbon/human/species/races/krootboys.dm
- code/modules/mob/living/carbon/human/species/races/nids.dm
- code/modules/mob/living/carbon/human/species/races/orks/abilities.dm
- code/modules/mob/living/carbon/human/species/races/tau.dm
Stamina breaks when it reaches 0 for some reason.
This prevents stamina from ever reaching 0 theoretically.
> Temp Stamina Fix

- code/modules/organs/external/_external.dm
you can now shred severed limbs into cutlets to create new limbs or food if you're desperate enough
> Limbs into cutlets

- code/modules/cargo/categories/blackmarket.dm
- code/modules/cargo/categories/weapons.dm
- code/modules/projectiles/guns/energy/laser.dm
Fixed the plasma gun cell issue. It works now.
Also edited some prices on merchant console.
> Plasma Bugfix

- code/modules/cargo/cargoterminal.dm
- code/modules/economy/cash.dm
**Whats new?!**
1) Spacecash renamed to scrip. Lore friendly currency.
2) Vendor machine that will help Noble to handle some trade operations
3) Noble can print scrip with holo-globe. Scrip is useless for interplanetary trade, but can be used as paper alternative to thrones for trade between the inhabitants of the planet.
> Vendor machines

- code/game/objects/structures/crates_lockers/crates.dm
- code/modules/cargo/categories/misc.dm
- code/modules/food/recipes_microwave.dm
You can buy a set of tools for ingot shaping in trading console
I also tried adding a new recipe to the microwave but it doesn't work yet. I don't know why, I'll figure it out later.
> new item in trading console

- code/modules/mob/living/carbon/human/species/station/skitarii.dm
- code/modules/projectiles/ammunition/boxes.dm
- code/modules/projectiles/guns/projectile/mattguns.dm
- maps/delta/warhammer-4.dmm
Fixes up some of the Skitarii issues temporarily until we have time to properly go over them. They aren't broken now, nor are they underpowered which is much more acceptable then being completely and utterly broken in power levels.
Fixed some lighting issues.
To Do: Go over the munitions for skitarii and properly balance them + do their stats/skills in a more precise manner. I cannot do this now due to someone already modifying the bullet files so it will happen later.
> Further Updoots

- code/__defines/mobs.dm
- code/_helpers/text.dm
- code/modules/mob/hear_say.dm
- code/modules/mob/living/say.dm
Fixes my previous fuck up with ghost chat. Also, ghost hearing is some of the most clown code i've ever fucking seen. I had to abstract the shit out of this but it works.
> Fixes ghost chat with ogryns

- code/modules/mob/datum_stats_skills.dm
> Skill description reworked (Rimworld inspired). Scaled up to 20

- code/modules/projectiles/guns/projectile/pistol.dm
- code/modules/projectiles/guns/projectile/sniper.dm
- code/modules/projectiles/projectile/bullets.dm
I added the Exitus in between my past PR and you merging it, so there were a couple of unresolved issues that this PR should fix.
(The warning's for a define that might be used later)
> Quick Exitus Mods

- code/modules/projectiles/guns/projectile/mattguns.dm
Updated the icon state so the Rad Carbine wouldn't be invisible anymore. Go crazy Skitarii.
> Rad Carbine Quick Fix

- code/modules/mob/new_player/new_player.dm
Updates the in game wiki link to be our new wiki, and turns "Grimdark" into "Forge-World Eipharius"
> Cherubael0.156

- code/modules/clothing/glasses/glasses.dm
- code/modules/clothing/head/helmet.dm
- code/modules/clothing/masks/gasmask.dm
- code/modules/clothing/suits/armor.dm
- code/modules/projectiles/guns/projectile/sniper.dm
> Vindicare armour and mask, goggles, and sniper slight modification.

- code/game/jobs/job/civilian.dm
Servitors can now intone the litanies of the machine god with Lingua-technis. All Hail the Omnissiah!
- Servitors speak Lingua-Technis as well as Low Gothic now.
> Servitors Language code update

- code/game/jobs/job/pilgrims.dm
- code/modules/projectiles/projectile/special.dm
Ogryno Ogryno.
buffs ogryn stats by a bit to make them stronger than humans and able to actually fight, DEXT = HOW MANY HITS YOU CAN ACTUALLY HIT
from str (17,20), dext(7,12), end(15,18), int (2,5) 
to str(19,22), dext(15,18), end(15,18), int (2,5)
Flamery flamer
- made rustwalkers unable to be put on fire by most flamer means for obvious reasons.
- nerfed phosphor gun to 25 fire stacks per tick, added 3 warnings on it about how stuff works and where it is being used(its not, yet, but from what i have quickly read, whoever is doing it didn't notice they were making a 1 shot kill gun).
- nerfed some fire stacks to 10 out of 50,
> fixes some shit, read desc

- code/game/jobs/job/magistratum.dm
> Adds a link to Messina Law to the Enforcer spawn text. 

- maps/delta/warhammer-1.dmm
> More Broke Ass Stairs

- code/game/jobs/job/astra_militarum.dm
read the files if you want to, its a quick read.
i changed stats and skills from sniper and specialist plus added the "SPECIALIST tag to the specialist name".
> Fixes Specialist Shit

- code/modules/mob/living/simple_animal/borer/borer_powers.dm
I don't even know, maybe this'll fix it?
> Revert "Borer slight changes"

- code/modules/mob/living/simple_animal/borer/borer_powers.dm
> Revert "Revert "Borer slight changes""

- code/modules/projectiles/guns/energy/special.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
Added reagents and a Gauss Rifle.
> Reagents and more

- code/game/jobs/job/pilgrims.dm
Actually put Pilgrim Chance at 100.
> Actually fixes Pilgrim Cult Chance

- code/game/objects/effects/chem/chemsmoke.dm
- code/game/objects/effects/effect_system.dm
- code/game/objects/items/weapons/grenades/smokebomb.dm
Added in gas grenades, relevant reagents, etc. Have not yet worked out how to make the gas effect humans, unfortunately.
> Gas grenades WIP

- code/game/machinery/bioprinter.dm
- code/game/objects/items/trash.dm
- code/modules/materials/material_recipes.dm
- code/modules/reagents/reagent_containers/food/snacks.dm
Bioprinted organs cant be sold anymore, but you can use meat to produce corpse starch!
1) Find used can or make one from metal sheets
2) Delimb a corpse, cut his limbs with a knife multiple times untill you get raw cutlets
3) Process raw cutlets in microwave
4) Stuff microwaved cutlets into empty cans
5) Sell them to trading console or consume later
> Corpse starch producing

- code/game/jobs/job/rogue_traders.dm
Accidentally gave the Xeno Merc infinity slots, fixed.
> Fixes Mercenary Slots

- code/modules/mob/living/simple_animal/friendly/farm_animals.dm
You can breed grox. Even feral one. Just feed them with any plant and wait 10-15 minutes.
Localy tested
> Breedable grox

- code/modules/projectiles/ammunition/bullets.dm
- code/modules/projectiles/guns/energy/laser.dm
- code/modules/projectiles/guns/energy/special.dm
- code/modules/projectiles/guns/projectile/shotgun.dm
- code/modules/projectiles/projectile/bullets.dm
- code/modules/projectiles/projectile/energy.dm
- code/modules/projectiles/projectile/special.dm
> bit of balancing, bit of noting, bit of screaming-- just read the changes!

- code/game/mecha/combat/dreadnought.dm
- code/game/mecha/equipment/weapons/weapons.dm
Added in Dreadnought mecha (Icon is broken, you need to set it manually to the right file after spawn) and some new equipment for it.
> Dreadnoughts and weapons

- code/game/objects/auras/aura.dm
- code/modules/mob/living/carbon/human/species/races/astartes.dm
- code/modules/mob/living/carbon/human/unarmed_attack.dm
Hopefully fixed limb issues, changed some health values, testing out organ healing.
> Astartes rework.

- code/game/jobs/job/rogue_traders.dm
- code/modules/clothing/masks/gasmask.dm
- code/modules/clothing/shoes/miscellaneous.dm
- code/modules/clothing/under/jobs/civilian.dm
- code/modules/projectiles/projectile/bullets.dm
this shouldn't conflict with any PRs, **the clown is not added to in game yet cause it would cause a merge conflict**
> adds basics of clownery

- code/game/jobs/job/rogue_traders.dm
- code/modules/clothing/masks/gasmask.dm
- code/modules/clothing/shoes/miscellaneous.dm
- code/modules/clothing/under/jobs/civilian.dm
- code/modules/projectiles/projectile/bullets.dm
Reverts WoodenTucker/40K-Eipharius#468
multiple errors and edits required
> Revert "adds basics of clownery"

- maps/watchman/watchman-2.dmm
forgot to place a spawn for trade console. without this the items cant spawn
> speed merge TDM 

- code/game/objects/items/weapons/material/swords.dm
- code/game/objects/items/weapons/melee/energy.dm
- code/game/objects/items/weapons/melee/misc.dm
- code/game/objects/items/weapons/stunbaton.dm
- code/game/objects/items/weapons/weaponry.dm
Balanced melee weapon armour penetration with the armour rework. Made the Null rod gib Daemons on a hit.
> Balancing melee weapons, made Nullrod gib Daemons

- code/modules/clothing/suits/armor.dm
- code/modules/clothing/suits/astartes.dm
- code/modules/mob/living/living_defense.dm
- code/modules/projectiles/projectile/bullets.dm
- code/modules/projectiles/projectile/energy.dm
goes back to the old school armor, also undoes the damages and armor stats
> Reverted armor changes (WIP NEW ARMOR IS HERE)

- code/game/jobs/job/adeptus_mechanicus.dm
- code/game/jobs/job/rogue_trader_retinue.dm
- code/game/objects/items/devices/mechanicustoys.dm
- code/modules/projectiles/projectile/bullets.dm
> (MERGE)minor fixes to narth.

- code/game/mecha/mecha.dm
exitable mechs thank to Vik. Do note its all mechs. dreadnoughts are free now.
> exitable mechs

- code/modules/mob/transform_procs.dm
comments out proc/claw on zombie code, unused I think
> Fixes error on main

- code/modules/projectiles/guns/energy/laser.dm
- code/modules/projectiles/projectile/bullets.dm
- code/modules/projectiles/projectile/energy.dm
- code/modules/projectiles/projectile/special.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
- config/example/admins.txt
- removes firing delay from plasma weaponry to make them usable
- reverts some of my earlier mistakes on this PR that were caused by copium
- makes bolter bullets not stun
- adds two new WIP chemicals
- makes adrenaline work on dead people(bugfix)
- nerfs bolter explosion, it can't delete walls anymore
- gives bolter bullets proper AP
**- ADDS ADMIN.TXT BACK ON EXAMPLES KILL NYLON IF HE REMOVES IT AGAIN**
> lotsafixes and changes

- code/datums/trading/misc.dm
- code/game/objects/structures/crates_lockers/closets/secure/security.dm
- code/modules/clothing/shoes/miscellaneous.dm
- code/modules/cultist/runes/nganga.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
- code/modules/spells/spellbook/battlemage.dm
- code/modules/tanning.dm
- code/modules/xenoarcheaology/finds/find_spawning.dm
Fixes butchering, tree cutting, and probably some other stuff nobody uses.
> Knife fixes

- code/game/jobs/job/adeptus_ministorum.dm
- code/game/jobs/job/astra_militarum.dm
- code/game/jobs/job/pilgrims.dm
- code/game/objects/items/devices/mechanicustoys.dm
- code/game/objects/items/weapons/melee/energy.dm
- code/modules/mob/living/carbon/human/species/station/skitarii.dm
- code/modules/projectiles/guns/energy/special.dm
- code/modules/projectiles/guns/projectile/mattguns.dm
- code/modules/projectiles/guns/projectile/sniper.dm
- code/modules/projectiles/projectile/bullets.dm
- code/modules/projectiles/projectile/special.dm
Balances omnissian axe, gives it pen among other things.
Gives galvanic rifle a better desc, makes their bullets give EMP, gives it a AIM ability.
balances ogrino shit.
makes ecclesiarchy confessor and priest a bit more accurate to lore, confessor is a chad, priest is a nerdboy.
Nerfs shit-ster stats and skills, they aren't supposed to be the same as astartes in any way, as strong as they may be, over 20 is only for intelligence, endurance or modded people.
Nerfs Novice sister stats, while technically they JUST started training and never went to battle, they have now stats that are comparable to a guardsman cadet.
Balances phosphor blast pistol properly, its not TOO OP anymore.
nerfs power claw block chance.
> BALANCING: read description

- code/modules/projectiles/guns/energy/laser.dm
- code/modules/projectiles/guns/energy/special.dm
- code/modules/projectiles/guns/projectile/automatic.dm
- code/modules/projectiles/guns/projectile/mattguns.dm
- code/modules/projectiles/guns/projectile/pistol.dm
- code/modules/projectiles/guns/projectile/shotgun.dm
- code/modules/projectiles/guns/projectile/sniper.dm
I did this but I didn't touch energy guns cause from what I generally tested, they were fine and needed nothing
I did all the projectile guns that used magazines (I think), so they should all have their sprites update properly.
Also I think I'm supposed to put this judging from the other PRs
> Adding Update_Icon stuff to most of the projectile guns

- maps/delta/warhammer_areas.dm
Wake up pilgrim, we got a trader to rob
Fixed: Power issues. For now.
> Area V2 Hotfix

- code/modules/clothing/masks/gasmask.dm
gives masks their sprites back (b r u h)
makes skitarii+techpriest masks masks (WHY WERE THEY NOT MASKS BUT UNREMOVABLE HELMETS TAKING MASK SLOT? WHAT THE FUCK HAVE YOU DONE!)
> fixes gasmasks

- code/game/objects/items/weapons/grenades/chem_grenade.dm
- code/modules/clothing/masks/gasmask.dm
Gives gasmasks protection against corruption gas.[](url)
> Blightnade Gas Protection

- code/modules/clothing/glasses/hud.dm
replaces bay sprite of medhud to lore friendly monacle
> Replaces health hud sprite

- code/game/jobs/job/adeptus_ministorum.dm
Allows Progena to be Male again, also removes the Sister headdress from their spawns. These aren't full Sisters, they are children in Training that can go many ways!
> Allows Progena to be Male Again

- code/modules/cultist/components/hereticitem.dm
Forgot to edit the Claw since zombies move fast now.
> Claw Edit Fix

- code/game/jobs/job/pilgrims.dm
- code/game/objects/items/glassjar.dm
Updated Pilgrim Fates, less guns overall and some more money for the classes without weapons. A few fates have some melee weapons fitting their story.
Ratcatchers now have Jars, Jars can now hold rats. This is a good thing.
> Updates Fates and Jars

- code/modules/clothing/shoes/jobs.dm
Reverts WoodenTucker/40K-Eipharius#595
no compile
> Revert "Remove Kroot Foot Sprite"

- maps/delta/jobs/warhammer_jobs.dm
> Oopsie Doodles

- code/modules/clothing/shoes/jobs.dm
* Removes Kroot foot Icon
* Makes ork shoes No_slip
EDIT
Proof it works Ravenor, yee of little faith
> Xeno Feet Update

- code/game/jobs/job/pilgrims.dm
> pilgrim.dm fix

- code/game/jobs/job/pilgrims.dm
> Pilgrim Fix 2

- code/modules/mining/ingotcrafting.dm
SMETH.
(fixes crafting recipes)
> fixes all dis

- code/game/jobs/job/adeptus_ministorum.dm
- code/game/jobs/job/rogue_trader_retinue.dm
- code/modules/client/preference_setup/general/01_basic.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/species/races/astartes.dm
- code/modules/mob/living/carbon/human/species/races/ogryn.dm
- code/modules/mob/living/carbon/human/species/races/orks/ork_species.dm
- code/modules/mob/living/carbon/human/species/races/tau.dm
- code/modules/mob/new_player/new_player.dm
THE SISTERS ARE NAKED.
THEY HAVE NO STATS.
> Revert "Added ability to change name on otherwise random or unfitting roles."

- code/modules/cultist/effects/khorne.dm
- code/modules/mob/living/carbon/human/examine.dm
- code/modules/mob/living/carbon/human/species/races/zombie.dm
> changes examination code, zombies and khorne exam BS

- code/modules/cultist/effects/khorne.dm
- code/modules/mob/living/carbon/human/examine.dm
- code/modules/mob/living/carbon/human/species/races/zombie.dm
Reverts WoodenTucker/40K-Eipharius#635
Examine text was broken
> Revert "changes examination code, zombies and khorne exam BS"

- code/game/jobs/job/astra_militarum.dm
> Recruit Slot Increase

- code/modules/projectiles/projectile/bullets.dm
nerfed ork bullets a LOT, will have to test
> Ork weapon nerf

- code/game/objects/items/devices/whistle.dm
Removed the whistle that has been preventing successful compiling for 2+ days since the author has failed to do so.
> Whistle Fix

- code/game/objects/random/random.dm
Forgot to include a small new random element that's been added across the map, sorry about that.
> Urgent hotfix

- code/game/machinery/cell_charger.dm
Removed 3 lines of code preventing cell_rechargers to function with our current power situation.
> Recharger Fix

- code/game/jobs/job/pilgrims.dm
- code/game/jobs/job/rogue_trader_retinue.dm
- code/modules/clothing/suits/armor.dm
- code/modules/mob/living/carbon/human/unarmed_attack.dm
- code/modules/projectiles/ammunition/boxes.dm
- code/modules/projectiles/guns/projectile/mattguns.dm
- code/modules/virus2/effect.dm
Further improvements to the previous Sub-Fate system.
Minor game fixes like zombie rending claws being able to decap someone in power armor and the Aegis rifle using the wrong ammo.
Also fixed up Nurgle Plague to be much more interesting.
> Pre-Host Update

- code/modules/projectiles/guns/projectile/pistol.dm
Changes the desc from 9mm to .45 as is in line with what the pistols actual caliber is.
> Update the wording on pistol.dm

- code/modules/rituals/ritual_handler.dm
Fixed a mismatch between ritual handler and config which caused one the rituals to not work.
> Fixed a mismatch between ritual handler and config

- code/game/jobs/job/adeptus_ministorum.dm
- code/game/jobs/job/inquisition.dm
- code/game/jobs/job/magistratum.dm
- code/game/mecha/equipment/weapons/weapons.dm
- maps/delta/warhammer-2.dmm
- maps/delta/warhammer-3.dmm
- maps/delta/warhammer-4.dmm
> Map Updates

- code/game/jobs/job/astra_militarum.dm
- code/game/jobs/job/pilgrims.dm
- code/modules/clothing/head/jobs.dm
- code/modules/clothing/shoes/ogryn.dm
- code/modules/clothing/suits/ogryn.dm
- code/modules/modular_computers/computers/subtypes/preset_console.dm
- code/modules/modular_computers/computers/subtypes/preset_laptop.dm
- code/modules/modular_computers/computers/subtypes/preset_tablet.dm
- maps/delta/warhammer-1.dmm
- maps/delta/warhammer-2.dmm
- maps/delta/warhammer-4.dmm
Added an Ogryn invisible head armor.
Removed crew records from all computers.
Further updates to the map regarding the Sondar House.
> Minor Update

- maps/delta/warhammer-1.dmm
- maps/delta/warhammer-5.dmm
- maps/delta/warhammer_areas.dm
Got pinged with some more bugs I wasn't aware of.
Solved snow issue with Farm Area.
Fixed Kroot and Tau spawns.
> Gol Darnit

- maps/delta/warhammer-1.dmm
- maps/delta/warhammer-2.dmm
- maps/delta/warhammer-3.dmm
- maps/delta/warhammer-4.dmm
Reverses the Guard PDF Bunker move while retaining some of their improvements like the armory addition. Tried to edit the Manor in a way that the Guard will no longer be able to destroy the Governor's manor and forge a trenchline, instead having to use the blast door gates and sentry tower if they want -- which has a potential connection to a WIP parapet.
> The Reversing

- code/modules/shuttles/landmarks.dm
- maps/delta/warhammer_shuttles.dm
> Shuttle Fix

- code/game/jobs/job/pilgrims.dm
- code/modules/clothing/under/jobs/civilian.dm
- maps/delta/warhammer-2.dmm
- maps/delta/warhammer-3.dmm
- maps/delta/warhammer-4.dmm
Adds the Mechanicus Bondsman Role.
Makes the Village Medicae subservient to the Mechanicus Biologis.
The Biologis lab has been merged into the Village Medicae Clinic with mixed access.
Potentially fixed the RT shuttle.
> Mechanicus Bondsman Update

- code/modules/clothing/suits/toggles.dm
Fixes the Inquisitor Hood's lack of hair/beard coverage and gives it some appropriate armor for being power armor.
> Update toggles.dm: Inquisitor Hood

- maps/delta/warhammer-1.dmm
- maps/delta/warhammer-2.dmm
- maps/delta/warhammer-9.dmm
THIS PULL REQUEST MAKES THE ORK AND SEKITE LATEPARTIES SPAWN AT THE SIEGE OF VRAKS MAP.
> Sekite + Ork Lateparty edit

- code/datums/outfits/civilian.dm
- code/game/jobs/job/adeptus_ministorum.dm
- code/game/jobs/job/pilgrims.dm
- code/game/machinery/vending.dm
- code/modules/clothing/head/jobs.dm
- code/modules/clothing/suits/armor.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
- code/modules/reagents/reagent_containers/hypospray.dm
gives combat pilgrim roles IFAKs, gives PDF a low chance 'veteran' subclass. Buffs blood injectors. By doubling the capacity and injection rate.. Buffs Ateopine by making it stabilize and heal eye damage.
> Buffs Medical and Combat Pilgrim roles

- code/modules/mob/living/living_defense.dm
Temporarily reverts armor update until it's fixed.
> Temp Armor Revert

- code/modules/mob/living/living_defense.dm
Reverts WoodenTucker/40K-Eipharius#784
> Revert "Temp Armor Revert"

- maps/delta/warhammer-3.dmm
- maps/delta/warhammer-4.dmm
> SECOND BREAKFAST

- code/datums/outfits/jobs/science.dm
No more 1hit gun until I nerf it into the ground
> Makes explorator NOT a TDM role

- code/game/jobs/job/adeptus_ministorum.dm
- code/game/objects/effects/landmarks.dm
- code/modules/reagents/reagent_containers/hypospray.dm
- maps/delta/warhammer-4.dmm
Removes plasma cells from their backpack, was a old thing.
Adds their proper spawn point. Touches mapping.
Gives them gloves and boots, I forgot to add those.
Gives them an IFAK.
> Canoness Fixes + Minor Additions.

- maps/delta/warhammer-2.dmm
- maps/delta/warhammer-3.dmm
- maps/delta/warhammer-4.dmm
what the title says. Also makes water less ugly. Will change plants in the planters when I have sprites for them
> no more space holes, stairs are usable

- code/game/jobs/job/pilgrims.dm
- code/game/jobs/job/rogue_trader_retinue.dm
- code/game/objects/items/weapons/explosives.dm
- maps/delta/warhammer-3.dmm
- maps/delta/warhammer-4.dmm
> Sondar Sondar

- code/game/jobs/job/adeptus_astartes.dm
They are angels of the Emperor. Maybe bitches sometimes/
> Gives Astartes dead_inside

- code/modules/cultist/deities.dm
- code/modules/cultist/runes/tzeentch.dm
Updates a few files to remove the copied names of ritual datums, adds them to the list of faction-performable rituals.
> Fixes Tzeentch and Nurgle rituals

- code/game/jobs/job/adeptus_astartes.dm
- code/game/objects/newmap/key_paths.dm
- code/modules/research/designs.dm
Increases Combat_Tech for guns so people can't make them easily as easily now. Higher end weaponry are now more research intensive. No more mechanicus spamming out bolters easily.
Fixes Hab 2 keys.
Fixes Adeptus Astartes code for server.
> Minor fixes

- code/_helpers/radio.dm
- code/game/jobs/job/adeptus_astartes.dm
- code/game/jobs/job/civilian.dm
- code/game/jobs/job/pilgrims.dm
- code/game/jobs/job/rogue_trader_retinue.dm
- code/game/objects/items/devices/radio/encryptionkey.dm
- code/game/objects/items/devices/radio/headset.dm
- code/game/objects/items/weapons/grenades/explosive.dm
- code/modules/cargo/categories/ammo.dm
- code/modules/cargo/categories/weapons.dm
- code/modules/cultist/deities.dm
- code/modules/cultist/runes/khorne.dm
- code/modules/cultist/runes/nurgle.dm
- code/modules/cultist/runes/slaanesh.dm
- code/modules/cultist/runes/tzeentch.dm
- code/modules/library/manuals/manuals.dm
- code/modules/mob/living/say.dm
Cults can now exchange Radio headsets, for Radios with unique secret channels.
Khorne/Nurgle share the same channel.
Slaanesh/Tzeentch share their own version as well. Avoids too much crossover and widespread co-operation since the cults typically don't even really work together. Though I've found these cults are really good combinations RP wise.
Nurgle and Khorne tend to just want to raid the manor.
Slaanesh and Tzeentch are more about getting really good drip and tormenting people.
Added chaos marine loadouts. They get both channels.
Changed Vane Bondsman to 2 slots, from 3.
Scavenger to 4 slots, from 2.
Xeno Mercenary to 1 slot, from 2.
Added armor penetration value to fragmentation grenades.
Frag Grenades are still the king of damage.
But Krak is the only grenade with the strength to …
> Medium Update

- code/game/jobs/job/civilian.dm
- code/game/jobs/job/pilgrims.dm
- code/game/objects/effects/spawners/gibspawner.dm
- maps/delta/warhammer-3.dmm
- maps/delta/warhammer-4.dmm
> Access Fix

- code/modules/research/designs.dm
- code/modules/research/stock_parts.dm
Rebalances RnD for the admech
Stops them from being able to mass produce weaponry, changes the prices and removes plasma weaponry (they're commented out until further notice, not like they could produce them anyways.) 
Also added a debug item for deconstruction to give all of the major techs
> RnD re-balance

- code/game/jobs/job/adeptus_astartes.dm
> Updates Astartes text

- code/game/jobs/job/adeptus_astartes.dm
- code/game/jobs/job/adeptus_ministorum.dm
- code/modules/clothing/suits/astartes.dm
- code/modules/projectiles/ammunition/bullets.dm
- code/modules/projectiles/guns/projectile/mattguns.dm
- code/modules/projectiles/projectile/special.dm
Salamander flamers added.
Canoness melee skill increased. I do love missing my swings.
Apothecaries get plasma magazines since no bolter
> Astartes + Flamers + Canoness changes

- maps/delta/warhammer-3.dmm
- maps/delta/warhammer-4.dmm
garrison moved to the spaceport, administratum added where the garrison used to be, fixes a couple of mapping problems, probably adds more.
> moves garrison, adds administratum building, space TSA,

- code/modules/reagents/reagent_containers/hypospray.dm
> Quick Icon fix - Apothecary injector

- code/game/jobs/job/adeptus_mechanicus.dm
- code/game/jobs/job/adeptus_ministorum.dm
- code/game/jobs/job/astra_militarum.dm
- code/game/jobs/job/civilian.dm
- code/game/jobs/job/governorship.dm
- code/game/jobs/job/inquisition.dm
- code/game/jobs/job/magistratum.dm
- code/game/jobs/job/pilgrims.dm
- code/game/jobs/job/rogue_trader_retinue.dm
- maps/delta/warhammer_areas.dm
Adds ideologies to certain jobs in the game which is selected via a Verb.
> Ideology Update

- code/modules/mob/living/carbon/human/species/races/orks/ork_species.dm
Reverts WoodenTucker/40K-Eipharius#879
> Revert "Ork Balance"

- code/game/mecha/mech_fabricator.dm
RT and his crew have a exosuit fabricator in their lab, but no access to it. This PR fixing this
> Access to exosuit fabricator

- code/modules/organs/internal/brain.dm
- code/modules/organs/internal/eyes.dm
- code/modules/organs/internal/heart.dm
- code/modules/organs/internal/kidneys.dm
- code/modules/organs/internal/liver.dm
- code/modules/organs/internal/lungs.dm
A common exploit where you could make infinite money by printing robotic organs with metal.
> Prosthetic organs cannot be sold anymore

- code/game/objects/items/devices/flashlight.dm
- code/modules/clothing/ears/earrings.dm
- code/modules/mining/ingotcrafting.dm
- code/modules/reagents/reagent_containers/food/drinks/bottle.dm
Following changes:
Three new recipes with silver: Candelabra, earrings and goblet. Each recipe is more expensive but takes longer to make.
Gold: Adds goblet, fixes golden rings not being able to be made with hammers.
Adds value to silver and golden goblets, as well candelabras.
> More crafting recipes

- code/modules/mining/ingotcrafting.dm
- code/modules/mining/oresningots.dm
Fixed some crafting issues from last rp
lowered value of ingots, rare metals should be sold to the mechanicus instead of the inn/trader.
There are recipes to make valuable stuff with other ingots, instead of just selling them raw. 
Should make less pilgrims get full power armor 10 minutes into the round, and gives them more stuff to do too.
> Crafting fix and ingot price rebalanced

- code/game/objects/newmap/dungeon_ship.dm
- code/modules/clothing/gloves/miscellaneous.dm
- code/modules/clothing/masks/gasmask.dm
- code/modules/clothing/spacesuits/captain.dm
- code/modules/clothing/spacesuits/miscellaneous.dm
- code/modules/clothing/suits/astartes.dm
- code/modules/clothing/under/accessories/armor.dm
- code/modules/clothing/under/jobs/security.dm
- code/modules/clothing/under/ogryn.dm
- code/modules/cultist/effects/khorne.dm
- code/modules/cultist/effects/slaanesharm.dm
- code/modules/cultist/runes/rune_types.dm
- maps/shared/items/clothing.dm
> Melee Fixes + Cult Rune + Khorne Fix

- code/game/objects/auras/aura.dm
- code/modules/cargo/categories/blackmarket.dm
- code/modules/clothing/rings/rings.dm
Artifacus Xenos Horrificus e Calixo Sector intra Ordos Xenos Radius increpuit et venditus in foro nigro pro incommodo pretio obstante magnitudine.
Compile tested
> The Poisoned Gifts From Long Past Stars

- code/game/objects/auras/aura.dm
- code/modules/cargo/categories/blackmarket.dm
- code/modules/clothing/rings/rings.dm
Reverts WoodenTucker/40K-Eipharius#905
> Revert "The Poisoned Gifts From Long Past Stars"

- code/game/objects/effects/landmarks.dm
- code/game/objects/items/devices/radio/encryptionkey.dm
- code/game/objects/items/devices/radio/headset.dm
- code/modules/cargo/categories/ammo.dm
- code/modules/cargo/categories/energy.dm
- code/modules/cargo/categories/weapons.dm
- code/modules/cargo/categories2/ammo.dm
- code/modules/clothing/suits/armor.dm
- code/modules/projectiles/ammunition/boxes.dm
- code/modules/projectiles/guns/energy/special.dm
- code/modules/projectiles/guns/projectile/shotgun.dm
- code/modules/projectiles/projectile/bullets.dm
- code/modules/research/designs.dm
- maps/delta/warhammer-2.dmm
- maps/delta/warhammer-4.dmm
- maps/delta/warhammer-5.dmm
- maps/delta/z (2).dmm
Removes the old lasgun melta, I plan on returning it, but till then it will be disabled.
Governor was not given Magisterium comms, fixed that.
> Removes old melta, Gov Magisterium comms

- maps/delta/warhammer-2.dmm
> fixes mechanicus stairs

- code/modules/clothing/head/jobs.dm
- code/modules/clothing/suits/armor.dm
- code/modules/projectiles/ammunition/boxes.dm
- code/modules/projectiles/guns/projectile/mattguns.dm
- code/modules/projectiles/projectile/special.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
- code/modules/reagents/reagent_containers/hypospray.dm
Astartes Chem autoinjector given new chem
Salamander flamer fix
New Astartes chem
Made Tzeench clothing description more obvious.
> Misc Stuff.

- code/modules/projectiles/guns/projectile/mattguns.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
Gave proper fire delay to the Flamer for salamanders, as funny as it is. Gave it a burst delay because I forgot to.
Mendroxine now properly metabolizes at the wished amount, and buffed it's healing a bit. It used to literally not metabolize.
> Sally Flamer Changes and Mendroxine Changes
